---
- hosts: webservers
  become: true
  tasks:
    - name: Install Apache2
      yum:
        name: httpd
        state: present

    - name: Start Apache2
      service:
        name: httpd
        state: started

    - name: Add firewall rule for HTTP
      shell: iptables -A INPUT -p tcp --dport 80 -j ACCEPT
