---
- hosts: webservers
  become: true
  tasks:
    - name: Install Apache2
      yum:
        name: httpd
        state: present

    - name: Start Apache2
      service:
        name: httpd
        state: started

    - name: Add firewall rule for HTTP
      shell: iptables -A INPUT -p tcp --dport 80 -j ACCEPT

    - name: Copy index.html to Apache document root
      copy:
        src: "{{ ansible_env.HOME }}/demo_project12/index.html"
        dest: /var/www/html/index.html
